spring:
  application:
    name: springboot-ztq
    group: 714
    developer: zhengtianqi<郑天祺>
  #配置中心地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&sessionVariables=sql_mode=NO_ENGINE_SUBSTITUTION
    username: root
    password: root

server:
  port: 8080

#允许feign开启熔断器，默认未开启
feign:
  hystrix:
    enabled: true

