spring:
  application:
    name: springboot-ztq
    group: 714
    developer: zhengtianqi<郑天祺>
  #配置中心地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&sessionVariables=sql_mode=NO_ENGINE_SUBSTITUTION
    username: root
    password: root
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 30
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
    # Redis服务器连接密码（默认为空）
#    password:
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000
# tomcat端口
server:
  port: 8080



#允许feign开启熔断器，默认未开启
feign:
  hystrix:
    enabled: true
# 开启swagger
swagger:
  base-package: com.ztq.controller
  base-path: /api/v1/**
  description: swagger ui
  enabled: true
  exclude-path: /error, /ops/**
  title: springboot-ztq
  contact:
    email: 270490096@qq.com
    name: zhengtianqi

